### ISSUE TITLE
Application reliant on existence of "C:\AkashaScanner\AkashaScanner\wwwroot\."

### ISSUE THREAD

**Issue by floravsolomon** [akrios-d/AkashaScanner#3]
This fork is reliant on the existence of the directory "C:\AkashaScanner\AkashaScanner\wwwroot\." and crashes at runtime if this is not the install directory

**Comment by floravsolomon** [comment]
Scratch that, but still can't figure out exactly what the file structure is here. It looks like it's heavily reliant upon the directory tree that existed when it was first compiled.

**Comment by akrios-d** [comment]
Taking a look at this today. ty for reporting

**Comment by akrios-d** [comment]
Was about the way i published. Just republished and it tested on my side and looks fine. Let me know if you still have issues
