### ISSUE TITLE
Talent scanning is too spaced out, skipping talents

### ISSUE THREAD

**Issue by floravsolomon** [akrios-d/AkashaScanner#4]
When running character scan, the talent scan is moving too high to begin with and jumping too much between entries; the cursor usually hits the first and third talents on screen. Doesn't seem to be dependent on resolution.

**Comment by akrios-d** [comment]
Found the issue, was due the way i fixed to Xianyun. should be fixed by today.

**Comment by akrios-d** [comment]
Release v0.4.5 should fix the issue. Let me know
