### ISSUE TITLE
"Song of Days Past" circlets are scanned as "Invalid", breaking export

### ISSUE THREAD

**Issue by blvz** [akrios-d/AkashaScanner#7]
**Describe the bug**
The app breaks when exporting to GOOD, because some artifacts are invalid. I only saw problems with "Song of Days Past" circlets. On the scanned data JSON they have both `Slot` and `MainStat` set as `Invalid`. After fixing those manually, the export works.

**To Reproduce**
1. Have "Song of Days Past" circlets on inventory
2. Perform an artifact scan
3. Try to export to GOOD
5. Check the artifacts json inside ScannedData directory

**Comment by akrios-d** [comment]
Thanks for the reporting. I ll be taking a look at it today

**Comment by akrios-d** [comment]
Fixed in release v0.4.6, let me know if find any issues.
